substitutions:
  device_name: main-bed
  friendly_name: Main Bed
  device_description: "Main Bed Pressure Sensor"

esphome:
  name: '${device_name}'
  comment: '${device_description}'

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TWEYVAvxT0WISQuKo01uMCF/23W79qhmBaShS5hvO1Y="

ota:
  password: "dc57bd34072c782d5d77a13bbae589d3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Main-Bed Fallback Hotspot"
    password: "MeDd4OnIncNs"

captive_portal:

improv_serial:

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      inverted: true
      mode:
        input: true
        pullup: true
    name: Rui
    icon: mdi:bed
  - platform: gpio
    pin:
      number: 14
      inverted: true
      mode:
        input: true
        pullup: true
    name: Patricia
    icon: mdi:bed

      
####################
######BT PROXY######

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
    
