# Home Assistant Pressure Mat
#
#Bed or Doormat sensor
#
#
substitutions:
  device_name: catarina-bed
  friendly_name: Catarina Bed
  device_description: "Pressure Sensor"

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0c6ec4b4830dd9a7a492c8610f4ab7dc"


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Catarina-Bed Fallback Hotspot"
    password: "Rvrdo4dC2dr6"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: 15
      inverted: true
      mode:
        input: true
        pullup: true
    name: '${device_name}'
    
